# pyre-ignore[21]
from firebase.client import get_db
# pyre-ignore[21]
from services.gemini_service import explain_alert
from datetime import datetime, timedelta
# pyre-ignore[21]
import httpx, os, math

AI_URL = os.getenv('AI_MODEL_URL', 'http://localhost:8001')
Z = 1.645 # 95% service level

import asyncio

from firebase.cache import get_cached_collection

async def generate_alerts():
    products = {d.id:d.to_dict() for d in get_cached_collection('products_active')}
    inventory = {d.id:d.to_dict() for d in get_cached_collection('inventory')}
    thresholds = {d.id:d.to_dict() for d in get_cached_collection('thresholds')}
    
    # Fetch forecasts generated by the Python AI engine
    forecasts = {d.id:d.to_dict() for d in get_cached_collection('forecasts')}

    results = []
    gemini_tasks = []
    # Rate limit to protect Google Free Tier (15 RPM) and ensure fast page loads
    MAX_GEMINI = int(os.getenv('MAX_GEMINI_CALLS_PER_REQUEST', 4))
    advice_cache = {}

    async with httpx.AsyncClient(timeout=30.0) as client:
        for sku, prod in products.items():
            cs = int(inventory.get(sku, {}).get('current_stock', prod.get('current_stock', 0)))
            lt = int(prod.get('lead_time_days', 5))
            
            # Extract AI Model truths instead of re-calculating from raw sales to save API quotas
            fc = forecasts.get(sku, {})
            is_cold = fc.get('is_cold', prod.get('cold_start', True))
            
            if not is_cold:
                avg = fc.get('forecast_30d', 0) / 30.0 if fc.get('forecast_30d', 0) > 0 else 0.01
                std = 0.5 # Default safety standard deviation assumption
                mode, confidence = 'MODEL', fc.get('confidence', 'HIGH')
            else:
                avg = 1.0 # Minimal fallback for cold start items
                std = 0.3
                mode, confidence = 'COLD-START', 'LOW (category proxy)'
            
            # Reorder calculations
            thr = thresholds.get(sku, {})
            
            # pyre-ignore
            ss = round(Z * std * math.sqrt(lt), 2)
            # pyre-ignore
            math_rp = round(avg*lt + ss, 2)
            math_proj = cs - avg*7
            # pyre-ignore
            math_days = round(cs/avg, 1) if avg > 0 else 999
            
            # Default fallback logic
            rp = math_rp
            proj = math_proj
            days = math_days
            
            # 1. AI FORECAST PRIORITY
            if fc and fc.get('confidence') == 'HIGH':
                ai_7d = fc.get('forecast_7d', avg*7)
                ai_avg = ai_7d / 7 if ai_7d > 0 else avg
                
                proj = cs - ai_7d
                # pyre-ignore
                rp = round(ai_avg*lt + ss, 2)
                # pyre-ignore
                days = round(cs/ai_avg, 1) if ai_avg > 0 else 999
                mode = '🧠 AI FORECAST'
                confidence = 'HIGH'
            # 2. MATH FALLBACK / COLD START
            else:
                mode = '🧮 MATH FALLBACK' if not is_cold else '❄️ COLD-START'
                
            # 3. MANUAL OVERRIDE PRIORITY (Trumps everything)
            if thr.get('reorder_point') is not None:
                rp = float(thr.get('reorder_point'))
                mode = '⚙️ MANUAL OVERRIDE'
                confidence = 'MANUAL'
                
            flag = int(proj <= rp)
            
            if flag and days <= lt: urgency = 'CRITICAL'
            elif flag and days <= lt*2: urgency = 'URGENT'
            elif flag: urgency = 'REORDER'
            else: urgency = 'OK'
            
            alert = {
                'sku':sku, 'product_name':prod.get('product_name',''),
                'category':prod.get('category',''), 'mode':mode,
                # pyre-ignore
                'current_stock':cs, 'avg_daily_demand':round(avg, 3),
                'days_of_stock':days, 'reorder_point':rp,
                'reorder_flag':flag, 'urgency':urgency, 'confidence':confidence,
                'days_to_graduate': max(0, 30-prod.get('sales_day_count',0)) if is_cold else 0,
                'acknowledged': inventory.get(sku, {}).get('acknowledged', False),
                'shap_factors': fc.get('shap_factors', [])
            }
            
            if flag and len(gemini_tasks) < MAX_GEMINI:
                # pyre-ignore
                gemini_tasks.append((alert, explain_alert(
                    # pyre-ignore
                    sku, prod.get('product_name',''), prod.get('category',''), cs, rp, round(avg*7, 1))))
            else:
                if flag:
                    print(f"DEBUG: Skipping Gemini for SKU {sku}. Count >= {MAX_GEMINI}")
                alert['explanation'] = 'Stock level has fallen below the safety reorder point.'
                
            results.append(alert)

    if gemini_tasks:
        print(f"DEBUG: Executing {len(gemini_tasks)} Gemini calls concurrently...")
        explanations = await asyncio.gather(*(task[1] for task in gemini_tasks))
        for i, (alert, _) in enumerate(gemini_tasks):
            alert['explanation'] = explanations[i]
            
    order = {'CRITICAL':0, 'URGENT':1, 'REORDER':2, 'OK':3}
    results.sort(key=lambda x: (order.get(x['urgency'],4), x['days_of_stock']))
    return results
