# pyre-ignore[21]
from firebase.client import get_db
# pyre-ignore[21]
from services.gemini_service import explain_alert
from datetime import datetime, timedelta
# pyre-ignore[21]
import httpx, os, math

AI_URL = os.getenv('AI_MODEL_URL', 'http://localhost:8001')
Z = 1.645 # 95% service level


def _to_float_safe(val, default=0.0):
    try:
        return float(val)
    except (TypeError, ValueError):
        return float(default)


def _to_int_safe(val, default=0):
    try:
        return int(val)
    except (TypeError, ValueError):
        return int(default)

import asyncio

from firebase.cache import get_cached_collection

async def generate_alerts():
    products = {d.id:d.to_dict() for d in get_cached_collection('products_active')}
    inventory = {d.id:d.to_dict() for d in get_cached_collection('inventory')}
    thresholds = {d.id:d.to_dict() for d in get_cached_collection('thresholds')}
    
    # Fetch forecasts generated by the Python AI engine
    forecasts = {d.id:d.to_dict() for d in get_cached_collection('forecasts')}

    # Load per-category safety factors (Z-scores) set by admin
    # Document ID = category name (e.g. 'Beverages'), field = safety_factor
    cat_safety = {d.id: float(d.to_dict().get('safety_factor', Z)) for d in get_cached_collection('categories')}

    results = []
    gemini_tasks = []
    # Rate limit to protect Google Free Tier (15 RPM) and ensure fast page loads
    MAX_GEMINI = int(os.getenv('MAX_GEMINI_CALLS_PER_REQUEST', 4))
    advice_cache = {}

    async with httpx.AsyncClient(timeout=30.0) as client:
        for sku, prod in products.items():
            cs = _to_int_safe(inventory.get(sku, {}).get('current_stock', prod.get('current_stock', 0)))
            lt = _to_int_safe(prod.get('lead_time_days', 5))
            
            # Extract AI Model truths instead of re-calculating from raw sales to save API quotas
            fc = forecasts.get(sku, {})
            is_cold = fc.get('is_cold', prod.get('cold_start', True))
            
            if not is_cold:
                forecast_30d = _to_float_safe(fc.get('forecast_30d', 0))
                avg = forecast_30d / 30.0 if forecast_30d > 0 else 0.01
                std = 0.5 # Default safety standard deviation assumption
                mode, confidence = 'MODEL', fc.get('confidence', 'HIGH')
            else:
                avg = 1.0 # Minimal fallback for cold start items
                std = 0.3
                mode, confidence = 'COLD-START', 'LOW (category proxy)'
            
            # Reorder calculations
            thr = thresholds.get(sku, {})
            
            # Use per-category Z (safety factor) set by admin, fallback to global Z=1.645
            Z_cat = cat_safety.get(prod.get('category', ''), Z)
            # pyre-ignore
            ss = round(Z_cat * std * math.sqrt(lt), 2)
            # pyre-ignore
            math_rp = round(avg*lt + ss, 2)
            math_proj = cs - avg*7
            # pyre-ignore
            math_days = round(cs/avg, 1) if avg > 0 else 999
            
            # Default fallback logic
            rp = math_rp
            proj = math_proj
            days = math_days
            
            # 1. AI FORECAST PRIORITY
            if fc and fc.get('confidence') == 'HIGH':
                ai_7d = _to_float_safe(fc.get('forecast_7d', avg*7))
                ai_avg = ai_7d / 7.0 if ai_7d > 0 else avg
                
                proj = cs - ai_7d
                # pyre-ignore
                rp = round(ai_avg*lt + ss, 2)
                # pyre-ignore
                days = round(cs/ai_avg, 1) if ai_avg > 0 else 999
                mode = '🧠 AI FORECAST'
                confidence = 'HIGH'
            # 2. MATH FALLBACK / COLD START
            else:
                mode = '🧮 MATH FALLBACK' if not is_cold else '❄️ COLD-START'
                
            # 3. MANUAL OVERRIDE PRIORITY (Trumps everything)
            if thr.get('reorder_point') is not None:
                rp = _to_float_safe(thr.get('reorder_point'))
                mode = '⚙️ MANUAL OVERRIDE'
                confidence = 'MANUAL'
                
            flag = int(proj <= rp)
            
            # 4. EMERGENCY RESTOCK PRIORITY (Absolute highest priority)
            inv_profile = inventory.get(sku, {})
            emergency_due_str = inv_profile.get('emergency_restock_due')
            is_emergency = False
            emergency_days = 0
            
            if emergency_due_str and cs <= 0:
                try:
                    # Clean the Z if present, ensure timezone info
                    from datetime import timezone
                    clean_str = emergency_due_str.replace('Z', '+00:00')
                    due_date = datetime.fromisoformat(clean_str)
                    now = datetime.now(timezone.utc)
                    emergency_days = round((due_date - now).total_seconds() / 86400.0, 1)
                    is_emergency = True
                except Exception as e:
                    print(f"DEBUG: Failed to parse emergency due date: {e}")
                    pass
            
            if is_emergency:
                urgency = 'EMERGENCY'
                flag = 1
                days = emergency_days
                mode = '🚨 EMERGENCY RESTOCK'
                confidence = 'CRITICAL OOS'
            elif flag and cs <= 0: urgency = 'CRITICAL'
            elif flag and days <= lt: urgency = 'URGENT'
            elif flag: urgency = 'REORDER'
            else: urgency = 'OK'
            
            active_avg = round(fc.get('forecast_7d', avg*7)/7, 3) if (fc and fc.get('confidence') == 'HIGH') else avg
            target_stock = rp + (active_avg * 30)
            rec_order = int(max(0, target_stock - cs)) if flag else 0

            alert = {
                'sku':sku, 'product_name':prod.get('product_name',''),
                'category':prod.get('category',''), 'mode':mode,
                # pyre-ignore
                'current_stock':cs, 'avg_daily_demand':round(avg, 3),
                'days_of_stock':days, 'reorder_point':rp,
                'reorder_flag':flag, 'urgency':urgency, 'confidence':confidence,
                'recommended_order_quantity': rec_order,
                'days_to_graduate': max(0, 30-prod.get('sales_day_count',0)) if is_cold else 0,
                'acknowledged': inv_profile.get('acknowledged', False),
                'shap_factors': fc.get('shap_factors', []),
                'unit_price': _to_float_safe(prod.get('unit_price', 0.0))
            }
            
            if flag and len(gemini_tasks) < MAX_GEMINI:
                # pyre-ignore
                gemini_tasks.append((alert, explain_alert(
                    # pyre-ignore
                    sku, prod.get('product_name',''), prod.get('category',''), cs, rp, round(avg*7, 1))))
            else:
                if flag:
                    print(f"DEBUG: Skipping Gemini for SKU {sku}. Count >= {MAX_GEMINI}")
                
                if is_emergency:
                    alert['explanation'] = 'Customer backorder created during inventory shortage. Immediate restock required to fulfill order before SLA expires.'
                else:
                    alert['explanation'] = 'Stock level has fallen below the safety reorder point.'
                
            results.append(alert)

    if gemini_tasks:
        print(f"DEBUG: Executing {len(gemini_tasks)} Gemini calls concurrently...")
        explanations = await asyncio.gather(*(task[1] for task in gemini_tasks))
        for i, (alert, _) in enumerate(gemini_tasks):
            if alert['urgency'] == 'EMERGENCY':
                alert['explanation'] = 'Customer backorder created during inventory shortage. Immediate restock required to fulfill order before SLA expires.'
            else:
                alert['explanation'] = explanations[i]
            
    order = {'EMERGENCY':-1, 'CRITICAL':0, 'URGENT':1, 'REORDER':2, 'OK':3}
    results.sort(key=lambda x: (order.get(x['urgency'],4), x['days_of_stock']))
    return results
